#!/bin/bash
TIMESTAMP=$(date '+%F-%T')
EXAMPLEDIR=../../dataset/examples
OUTDIR=$EXAMPLEDIR/out/outsynth1/$TIMESTAMP
EXAMPLES=$1
CONSTS=$2

mkdir -p $OUTDIR
touch $OUTDIR/command.txt
printf '%s\n' "python runbench.py -t 600 -m 16 -d $OUTDIR -e $EXAMPLES -ci $CONSTS -cs $CONSTS" > $OUTDIR/command.txt

python runbench.py -t 600 -m 16 -d $OUTDIR -e $EXAMPLES -ci $CONSTS -cs $CONSTS $EXAMPLEDIR/examples-{01..25}.json &
python runbench.py -t 600 -m 16 -d $OUTDIR -e $EXAMPLES -ci $CONSTS -cs $CONSTS $EXAMPLEDIR/examples-{26..50}.json &
python runbench.py -t 600 -m 16 -d $OUTDIR -e $EXAMPLES -ci $CONSTS -cs $CONSTS $EXAMPLEDIR/examples-{51..75}.json &
python runbench.py -t 600 -m 16 -d $OUTDIR -e $EXAMPLES -ci $CONSTS -cs $CONSTS $EXAMPLEDIR/examples-{76..95}.json &
