#!/bin/bash
TIMESTAMP=$(date '+%F-%T')
OUTDIR=out/$TIMESTAMP
EXAMPLES=$1
CONSTS=$2
EXDIR=

mkdir -p $OUTDIR
touch $OUTDIR/command.txt
printf '%s\n' "python runbench.py -t 600 -m 16 -d $OUTDIR -e $EXAMPLES -c $CONSTS" > $OUTDIR/command.txt

python runbench.py -t 600 -m 16 -d $OUTDIR -e $EXAMPLES -c $CONSTS ../../dataset/examples/examples-{01..12}.json &
python runbench.py -t 600 -m 16 -d $OUTDIR -e $EXAMPLES -c $CONSTS ../../dataset/examples/examples-{13..24}.json &
python runbench.py -t 600 -m 16 -d $OUTDIR -e $EXAMPLES -c $CONSTS ../../dataset/examples/examples-{25..36}.json &
python runbench.py -t 600 -m 16 -d $OUTDIR -e $EXAMPLES -c $CONSTS ../../dataset/examples/examples-{37..48}.json &
python runbench.py -t 600 -m 16 -d $OUTDIR -e $EXAMPLES -c $CONSTS ../../dataset/examples/examples-{49..60}.json &
python runbench.py -t 600 -m 16 -d $OUTDIR -e $EXAMPLES -c $CONSTS ../../dataset/examples/examples-{61..72}.json &
python runbench.py -t 600 -m 16 -d $OUTDIR -e $EXAMPLES -c $CONSTS ../../dataset/examples/examples-{73..84}.json &
python runbench.py -t 600 -m 16 -d $OUTDIR -e $EXAMPLES -c $CONSTS ../../dataset/examples/examples-{85..95}.json &
